### ISSUE TITLE
Since Yesterday got Failed

### ISSUE THREAD

**Issue by Roughtrade** [chriszero/tvspielfilm2xmltv#12]
`07:58:36 INFO::Prepare grabbing...
07:58:36 INFO::Start grabbing...
07:58:39 ERROR::tvspielfilm2xmltv.py:
TypeError("cannot concatenate 'str' and 'datetime.date' objects",)
Traceback (most recent call last):
  File "/usr/share/tvspielfilm2xmltv/tvspielfilm2xmltv.py", line 134, in main
    grabber.start_grab()
  File "/usr/share/tvspielfilm2xmltv/tvsp2xmltv/tvsGrabber.py", line 70, in start_grab
    self.__grab_day(day, tvsp_id, chan_id)
  File "/usr/share/tvspielfilm2xmltv/tvsp2xmltv/tvsGrabber.py", line 92, in __grab_day
    logger.log("Failed to fetch Channel " + tvsp_id + " at " + date, logger.WARNING)
TypeError: cannot concatenate 'str' and 'datetime.date' objects
`
Your wonderful Script was runnig perfect since yesterday. It runs with a cronjob on 2 raspberry Pis.

A view weeks ago i could solve a Problem by installing:
`sudo apt-get install build-essential python-dev libffi-dev libssl-dev
sudo pip install urllib3[secure]`

Sorry my English is not the best.
Regards Peter

**Comment by chriszero** [comment]
Hallo,
Es gab wohl eine Änderungen bei der API, muss ich mir das genauer anschauen.

**Comment by Roughtrade** [comment]
Ich schreib mal in Deutsch. Ich habe jetzt mal in der Config die Image Grüße auf 4 eingestellt und beim Grabben Kabel1 rausgeschmissen. Jetzt lädt mein Pi schon mal wieder einige Kanäle.

`tvspielfilm2xmltv 2 '' 1 ard.de zdf.de rtl.de prosieben.de sat1.de vox.de kabele n24.de tele5.de 3sat.de arte.de phoenix.de ndr.de mdr.de wdr.de bayern3.de hesde zdfinfo.de ard-alpha.de zdfkultur.de`

läuft durch

**Comment by chriszero** [comment]
Habe die Url's der API angepasst und die Senderliste geupdated.
Da sind viele Änderungen, auf alle Fälle channelmap überprüfen!
