### ISSUE TITLE
Leider bekomme ich jetzt einen Fehler 

### ISSUE THREAD

**Issue by Roughtrade** [chriszero/tvspielfilm2xmltv#13]
`  File "/usr/local/bin/tvspielfilm2xmltv", line 37
    __version__ = 0.0.9
                      ^
SyntaxError: invalid syntax
`
Hallo entschuldige, aber ich bekomme jetzt folgenden Fehler wenn ich den Controllfile erstellen will.
P.S.: ich habe Python 2.7.6

**Comment by Roughtrade** [comment]
Ich habe die Zeile 37 geändert in:
`__version__ = '0.0.9'`

jetzt geht es, vielen Dank für Deine Aktualisierung

**Comment by chriszero** [comment]
Fixed
